"""Pydantic models for structured LLM output and the LangGraph state definition.

Every node in the research report graph reads from and writes to `ResearchState`.
The Pydantic models define the structured output schemas the LLM is asked to produce.
"""

import operator
from typing import Annotated, Literal, Optional

from pydantic import BaseModel, Field
from typing_extensions import TypedDict


# ---------------------------------------------------------------------------
# Pydantic models — structured output schemas for LLM calls
# ---------------------------------------------------------------------------

class ResearchSection(BaseModel):
    """A single section in the research plan."""
    title: str = Field(description="Section heading for the report")
    description: str = Field(description="What this section should cover and why it matters")
    search_queries: list[str] = Field(
        description="2-3 targeted search queries to research this section"
    )


class ResearchPlan(BaseModel):
    """Structured research plan generated by the planner node."""
    title: str = Field(description="Professional report title")
    executive_summary_prompt: str = Field(
        description="What the executive summary should address"
    )
    sections: list[ResearchSection] = Field(
        description="Ordered list of 4-6 report sections"
    )
    suggested_charts: list[str] = Field(
        description="Types of charts/visualizations that would enhance the report "
        "(e.g. 'bar chart comparing market share', 'timeline of key events')"
    )
    urls_to_screenshot: list[str] = Field(
        description="Up to 5 URLs worth capturing screenshots of for the report"
    )


class SearchResult(BaseModel):
    """A single web search result associated with a report section."""
    query: str
    url: str
    title: str
    content: str
    section: str  # which report section this result belongs to


class ChartSpec(BaseModel):
    """Specification for a chart the LLM wants generated.

    The LLM describes *what* to chart; deterministic Python code handles *how*.
    """
    title: str = Field(description="Chart title")
    chart_type: str = Field(
        description="One of: bar, horizontal_bar, line, pie, heatmap, scatter"
    )
    data: dict = Field(
        description="Chart data. For bar/line: {'labels': [...], 'values': [...]}. "
        "For pie: {'labels': [...], 'sizes': [...]}. "
        "For scatter: {'x': [...], 'y': [...]}. "
        "For heatmap: {'labels': [...], 'matrix': [[...]]}."
    )
    description: str = Field(description="One-sentence caption explaining the chart")
    section: str = Field(description="Which report section this chart belongs to")


class DataAnalysis(BaseModel):
    """Structured analysis output from the data analyst node."""
    key_findings: list[str] = Field(
        description="5-10 key findings from the research"
    )
    data_points: list[dict] = Field(
        description="Extractable quantitative data points for tables/charts"
    )
    chart_specs: list[ChartSpec] = Field(
        description="Specifications for 2-4 charts to generate"
    )
    summary_table: dict = Field(
        description="Summary table data as {'columns': [...], 'rows': [[...], ...]}"
    )


class ChartData(BaseModel):
    """A rendered chart with its base64-encoded PNG image."""
    title: str
    base64_png: str
    description: str
    section: str


class ScreenshotData(BaseModel):
    """A web page screenshot with its base64-encoded PNG image."""
    url: str
    base64_png: str
    caption: str


class QualityReview(BaseModel):
    """Quality assessment of the report draft, used for conditional routing."""
    is_complete: bool = Field(description="Whether the report is complete enough to publish")
    missing_areas: list[str] = Field(
        description="Specific areas that need more research or detail"
    )
    needs_more_data: bool = Field(
        description="Whether more quantitative data or charts are needed"
    )
    route_to: Literal["compiler", "web_researcher", "data_analyst"] = Field(
        description="'compiler' if done, 'web_researcher' if needs more research, "
        "'data_analyst' if needs more analysis/charts"
    )


# ---------------------------------------------------------------------------
# Graph State — the TypedDict that flows through the LangGraph
# ---------------------------------------------------------------------------

class ResearchState(TypedDict):
    """The state that flows through the research report graph.

    Keys with `Annotated[list, operator.add]` use a **reducer** — each node
    invocation *appends* to the list instead of overwriting it. This is how
    search results, charts, and screenshots accumulate across multiple node calls.
    """
    topic: str
    research_plan: Optional[ResearchPlan]
    search_results: Annotated[list[SearchResult], operator.add]
    analysis: Optional[DataAnalysis]
    charts: Annotated[list[ChartData], operator.add]
    screenshots: Annotated[list[ScreenshotData], operator.add]
    report_sections: dict[str, str]  # section_title → written content (override)
    final_report_html: str
    iteration_count: int
    max_iterations: int
    status: str
